%Doctor.Config{
  ignore_modules: [
    TaleForge.Accounts.User,
    TaleForge.Accounts.UserToken,
    TaleForge.Repo,
    TaleForgeWeb,
    TaleForgeWeb.Endpoint,
    TaleForgeWeb.ErrorHTML,
    TaleForgeWeb.ErrorJSON,
    TaleForgeWeb.PageController,
    TaleForgeWeb.PageHTML,
    TaleForgeWeb.Router,
    TaleForgeWeb.Telemetry,
    TaleForgeWeb.UserConfirmationInstructionsLive,
    TaleForgeWeb.UserConfirmationLive,
    TaleForgeWeb.UserForgotPasswordLive,
    TaleForgeWeb.UserLoginLive,
    TaleForgeWeb.UserRegistrationLive,
    TaleForgeWeb.UserResetPasswordLive,
    TaleForgeWeb.UserSessionController,
    TaleForgeWeb.UserSettingsLive
  ],
  ignore_paths: [],
  min_module_doc_coverage: 40,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 50,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 0,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: true,
  umbrella: false,
  failed: false
}
